name: Vercel Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  Merge-Master-to-Vercel-Release:
    runs-on: ubuntu-latest
    env:
      GHBUSER: ${{ secrets.GHBUSER }}
      GHBEMAIL: ${{ secrets.GHBEMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initiate NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Installing pnpm
        run: |
          npm install -g pnpm@10.10.0

      - name: Configure Git
        run: |
          git config user.name "$GHBUSER"
          git config user.email "$GHBEMAIL"

      - name: Merge master into release/vercel (force use master content)
        run: |
          git fetch origin
          git checkout release/vercel
          git merge -s ours origin/release/vercel -m "ci(release/vercel): mark base"
          git merge origin/master -s recursive -X theirs -m "ci(release/vercel): auto-merge from master to release/vercel"

      - name: Install modules
        run: |
          pnpm install
      
      - name: Builds
        run: |
          pnpm dev:test
          pnpm dev:format
          pnpm dev:lint
          pnpm build
      
      - name: Additional Git Commands
        run: |
          git add -f dist/
          if ! git diff --quiet dist/; then
            git commit -m "ci(release/vercel): builds"
          else
            echo "No changes in dist directory"
          fi

      - name: Push to release/vercel
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release/vercel