name: Vercel Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  Merge-Master-to-Vercel-Release:
    runs-on: ubuntu-latest
    env:
      GHBUSER: ${{ secrets.GHBUSER }}
      GHBEMAIL: ${{ secrets.GHBEMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initiate NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Installing pnpm
        run: npm install -g pnpm@10.10.0

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Prepare release folder
        run: |
          mkdir release
          cp -r dist package.json vercel.json pnpm-lock.yaml release/

      - name: Commit and push to release/vercel
        working-directory: release
        run: |
          git init
          git config user.name "$GHBUSER"
          git config user.email "$GHBEMAIL"
          git add .
          git commit -m "ci(release/vercel): release build from master"
          git branch -M release/vercel
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push -f origin release/vercel
